[theme]
primaryColor="#00B894"              # μεσαίο πράσινο
backgroundColor="#0B1B20"           # πολύ σκούρο πράσινο/μαύρο
secondaryBackgroundColor="#10252C"  # πιο ανοιχτό πράσινο
textColor="#F5F5F5"                 # πολύ ανοιχτό γκρι-πράσινο
font="sans serif"